import type { NextPage } from "next";
import Head from "next/head";
import IntroMessage from "../components/IntroMessage";
import Exp from "../components/Question";

const ExpQuestion: NextPage = () => {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Exp />
    </>
  );
};

export default ExpQuestion;
