import type { NextPage } from "next";
import Head from "next/head";
import styled from "styled-components";
import IntroMessage from "../components/IntroMessage";

const SBody = styled.div`
  display: flex;
  justify-content: center;
  background: #ffffff;
  height: 100vh;
`;

const SMain = styled.div`
  width: 100%;
  display: flex;
  flex-direction: column;
  max-width: 65rem;
  margin: 1rem;
  margin-top: 1.25rem;
`;

const SAppName = styled.p`
  font-size: 2.5rem;
  line-height: 2rem;
  margin-bottom: 4rem;
  font-weight: 500;
  color: #333333; ;
`;

const SBox = styled.div`
  display: flex;
  justify-content: space-between;
  align-items: center;
  flex-wrap: wrap;

  @media (max-width: 957px) {
    justify-content: center;
  } ;
`;

const SImg = styled.div`
  width: 25rem;
  height: 25rem;
  border-radius: 50%;
  /* overflow: hidden; */
  /* background-image: url("wallet.webp"); */
  background-color: #e384ea;

  @media (max-width: 957px) {
    margin: 5rem 0;
  } ;
`;

const Simg = styled.img`
margin-left: -40px;
  width: 29rem;
  /* border-radius: 50%; */
`;

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <SBody>
        <SMain>
          <SAppName>TokPock</SAppName>
          <SBox>
            <IntroMessage />
            <SImg>
              <Simg src="wallet.png" alt="" />
            </SImg>
          </SBox>
        </SMain>
      </SBody>
    </>
  );
};

export default Home;
