import type { NextPage } from "next";
import Head from "next/head";
import Withdrawal from "../components/Withdraw";

const Withdraw: NextPage = () => {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <>
        <Withdrawal />
      </>
    </>
  );
};

export default Withdraw;
